// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ9zuP_j5Joyg_Dw',
    appId: 'AIzaSyBJ9zuP_j5Joyg_Dw',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    authDomain: 'quickie-23ff0.firebaseapp.com',
    storageBucket: 'quickie-23ff0.appspot.com',
    measurementId: 'G-W3G8GEC2Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9zuP_j5Joyg_Dw',
    appId: 'AIzaSyBJ9zuP_j5Joyg_Dw',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    storageBucket: 'quickie-23ff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9zuP_j5Joyg_Dw',
    appId: '1:AIzaSyBJ9zuP_j5Joyg_Dwd7',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    storageBucket: 'quickie-23ff0.appspot.com',
    iosBundleId: 'com.example.quickie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ9zuP_j5Joyg_DwGQ',
    appId: '1:vAIzaSyBJ9zuP_j5Joyg_Dwb9ad0bd7',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    storageBucket: 'quickie-23ff0.appspot.com',
    iosBundleId: 'com.example.quickie.RunnerTests',
  );
}
