// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJdSi6k2b5R1jAGM4f19zuP_j5Joyg_Dw',
    appId: '1:73653702134:web:465c1a341771c85aad0bd7',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    authDomain: 'quickie-23ff0.firebaseapp.com',
    storageBucket: 'quickie-23ff0.appspot.com',
    measurementId: 'G-W3G8GEC2Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODNhy-nesi245QotRPzcbCHyN_S50vnY',
    appId: '1:73653702134:android:5a7f8f49086a4b37ad0bd7',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    storageBucket: 'quickie-23ff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6uQuqKV3Pe-no9xvsl1R6h-0NmUwOMGQ',
    appId: '1:73653702134:ios:6de6386f02722f23ad0bd7',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    storageBucket: 'quickie-23ff0.appspot.com',
    iosBundleId: 'com.example.quickie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6uQuqKV3Pe-no9xvsl1R6h-0NmUwOMGQ',
    appId: '1:73653702134:ios:a68a84491c089fb9ad0bd7',
    messagingSenderId: '73653702134',
    projectId: 'quickie-23ff0',
    storageBucket: 'quickie-23ff0.appspot.com',
    iosBundleId: 'com.example.quickie.RunnerTests',
  );
}